# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e79da5c31379fc9e12f70ed785746e0a8a1222071ebfab6a7038b718a0e1e998dff86476ed92b0d24151bb2b6511bee344d832ef45e189b177fbca926f38691

test:
  secret_key_base: 0f0b16265632121c44c52f00285222c51d4a7b1bc9df3abbd66992645ec7da75b722be9df8375ae68177feab2f3650d8f2656008682775b2afb018516eb0fea5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
